#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

mv $ADDED_DIR/entrypoint /
chmod +x /entrypoint

mv $ADDED_DIR/launch.sh $FLINK_HOME/bin/
chmod +x $FLINK_HOME/bin/launch.sh

# copy in live conf files
mv $ADDED_DIR/flink-defaults.conf $FLINK_HOME/conf/
mv $ADDED_DIR/log4j.properties $FLINK_HOME/conf/

# FLINK_WORKER_DIR defaults to FLINK_HOME/work and is created on
# Worker startup if it does not exist. instead of making FLINK_HOME
# world writable, create FLINK_HOME/work.
mkdir $FLINK_HOME/work
chmod a+rwx $FLINK_HOME/work

chmod -R a+rwX $FLINK_HOME
